spring:
  config: 
    import: optional:file:.env[.properties]
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
token:
  signing:
    key: ${JWT_SECRET:my-secret-key}